name: VCuber | Compile

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Compile with Nuitka
      uses: Nuitka/Nuitka-Action@v0.4
      with:
        script-name: main.py
        standalone: true
        onefile: true
        enable-plugins: tk-inter, numpy
        disable-console: true
        windows-icon-from-ico: ./icon.ico
        windows-company-name: Jilin University
        windows-product-name: VCuber
        windows-file-version: 0.0.0.1
        windows-file-description: A simple cube drawing program.


    - name: Deploy to pre-release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: latest
        files: |
          build/*.exe
